### ISSUE TITLE
change the database according to second meeting detail

### ISSUE THREAD

**Issue by rayanaradha** [dcs-university-of-jaffna/PIMS#30]
> Client gave flora, fauna, chemical 
> and pharmaceutical details.

- [x]  Add tables according to these details
- [x]  Add management and symptom details for above toxins
- [x]  Add seed files to generate test data

**Comment by ChamikaraTDP** [comment]
add flora details to db

**Comment by rayanaradha** [comment]
finish

**Comment by rayanaradha** [comment]
finish
